"""empty message

Revision ID: 3d93ee648860
Revises: 5089489eb52d
Create Date: 2018-08-25 13:01:26.694393

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3d93ee648860'
down_revision = '5089489eb52d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'chapter', type_='foreignkey')
    op.drop_column('chapter', 'uploader_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chapter', sa.Column('uploader_id', sa.INTEGER(), nullable=True))
    op.create_foreign_key(None, 'chapter', 'user', ['uploader_id'], ['id'])
    # ### end Alembic commands ###
